MESSAGE( "   · Adding: predefined signature macro" )

# Custom signature, edit, or comment this cmake.
MACRO(PRINTSIGNATURE SIGNATURE DATE)
  PRINT("")
  PRINT("   ***********************************************************************************************")
  PRINT("")
  PRINT("     oooOOOOOOOOOOO    ${SIGNATURE} ${DATE}                             ")
  PRINT("     o   ____          :::::::::::::::::: :::::::::::::::::: __|-----|__")
  PRINT("     Y_,_|[]| --++++++ |[][][][][][][][]| |[][][][][][][][]| |  [] []  |")
  PRINT("    {|_|_|__|;|______|;|________________|;|________________|;|_________|;")
  PRINT("     /oo--OO   oo  oo   oo oo      oo oo   oo oo      oo oo   oo     oo")
  PRINT("  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+")
  PRINT("")
  PRINT("   ***********************************************************************************************")
  PRINT("")
ENDMACRO()
